### ISSUE TITLE
Precompiled Nightly builds are missing node_modules/uglify-js

### ISSUE THREAD

**Issue by juj** [juj/emslave#1]
The `node_modules/` directories are currently filtered out from nightly uploads of Emscripten, because the idea was to install them on demand, but we actually don't install them on demand. Figure out if it's better to bundle them in or install on demand.

**Comment by trzecieu** [comment]
As a comment for uglify-js it looks that emscripten has a modified version. This makes nightly builds broken: https://github.com/kripken/emscripten/issues/4961

**Comment by juj** [comment]
Nightlies have been sunset, so this issue no longer applies.
